name: riverpod_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  common:
    path: ../common
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  go_router: ^15.1.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  retrofit: ^4.4.2
  riverpod_annotation: ^2.6.1
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  analyzer: 7.3.0
  build_runner: ^2.4.15
  fake_async: ^1.3.2
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  go_router_builder: ^2.9.0
  integration_test:
    sdk: flutter
  json_serializable: ^6.9.5
  mockito: ^5.4.5
  retrofit_generator: ^9.1.9
  riverpod_generator: ^2.6.5
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
