name: riverpod_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  common:
    path: ../common
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  freezed_annotation: ^3.0.0
  go_router: ^17.0.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  retrofit: ^4.9.0
  riverpod_annotation: ^3.0.0
  smooth_page_indicator: ^2.0.1

dev_dependencies:
  analyzer: ^8.0.0
  build_runner: ^2.4.0
  fake_async: ^1.3.2
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  go_router_builder: ^4.0.0
  integration_test:
    sdk: flutter
  json_serializable: ^6.9.5
  mockito: ^5.4.5
  # Unpin once this issue is resolved: https://github.com/trevorwang/retrofit.dart/issues/876
  retrofit_generator: 10.2.0
  riverpod_generator: ^3.0.0
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  generate: true
