name: bloc_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  common:
    path: ../common
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_cache_manager: ^3.4.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  go_router: ^17.0.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  retrofit: ^4.4.2
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  analyzer: 7.4.3
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  build_verify: ^3.1.0
  file: ^7.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  go_router_builder: ^2.7.1
  integration_test:
    sdk: flutter
  json_serializable: ^6.9.5
  mockito: ^5.4.5
  retrofit_generator: ^9.1.9
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
